### ISSUE TITLE
安装失败了，可否贴个简单的教程？

### ISSUE THREAD

**Issue by Huracan** [isrc-cas/rvv-llvm#2]
ubuntu16.04+gcc7.4 +10g RAM 安装报错
================================================================
[ 89%] Linking CXX executable ../../../../bin/clang
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
tools/clang/tools/driver/CMakeFiles/clang.dir/build.make:355: recipe for target 'bin/clang-10' failed
make[2]: *** [bin/clang-10] Error 1
make[2]: *** Deleting file 'bin/clang-10'
CMakeFiles/Makefile2:29899: recipe for target 'tools/clang/tools/driver/CMakeFiles/clang.dir/all' failed
make[1]: *** [tools/clang/tools/driver/CMakeFiles/clang.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 
==============================================================
能告诉我哪里出了问题嘛~？

PS:非常想试用rvv-llvm，但安装过程不太友好。能否贴一个简单的教程，包括环境和安装步骤，谢谢。

**Comment by lazyparser** [comment]
> collect2: fatal error: ld terminated with signal 9 [Killed]

这里失败的原因可能是内存不足，在linking的时候，需要大量的内存。

`make -j 8 || make -j 1`
或者用
ninja 的 BUILD_JOBS=9 LINK_JOBS=1 来解决这个问哦。

**Comment by lazyparser** [comment]
> PS:非常想试用rvv-llvm，但安装过程不太友好。能否贴一个简单的教程，包括环境和安装步骤，谢谢。

感谢反馈，我这边来添加下 wiki

**Comment by xingmingjie** [comment]
看下是不是你的硬盘空间不够了。

**Comment by Huracan** [comment]
谢谢各位大佬，我估计是RAM或者swap不太够用，现在我用Release模式安装成功了。
$  cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../llvm cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"    

------------------------------------------------------------------------------------------------

我现在可以通过C代码生成IR，然后用llc test.bc -o test.S -march=riscv64生成rv64的汇编代码，那么现在新的问题的是，如何由C代码或RISC-V汇编代码生成RISC-V可执行文件?
llvm的command确实不太熟，烦请各位指点下，谢谢！

**Comment by xingmingjie** [comment]
C代码，需要用clang，也就是说需要把llvm和clang都构建出来。

例如：

clang --target=riscv64 test.c

**Comment by xingmingjie** [comment]
简单教程已经更新到README中了。
