### ISSUE TITLE
Branch from which LLVM commit?

### ISSUE THREAD

**Issue by jinchenglee** [isrc-cas/rvv-llvm#3]
May I ask which commit is this repo branched from LLVM? It seems it is based on LLVM 10.0, however, it is different from the release branch. Thanks.

**Comment by jinchenglee** [comment]
It seems the majority of the code were from LLVM v9.0.

**Comment by lazyparser** [comment]
Hi the `rvv-iscas` was branched out from master branch. we intended to merge/rebase this branch periodically.

thanks for attention! issues or bug reports are welcome ❤️
