### ISSUE TITLE
This latest version doesn't support rvv 0.9

### ISSUE THREAD

**Issue by mamengjin** [isrc-cas/rvv-llvm#5]

**Comment by StephenFann** [comment]
Thanks your issue! Can you describe the issue in detail?

**Comment by xingmingjie** [comment]
Hi, @mamengjin. Current rvv-iscas branch is based on llvm upstream. So the clang's command option should be `-menable-experimental-extensions -march=rv64gcv0p9`. The 0p9 is used to specify RVV version 0.9.

**Comment by mamengjin** [comment]
Thanks a lot, it works well using the above command
